title: Acyclovir and hydrocortisone (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Xerese
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Acyclovir and hydrocortisone topical combination is used to treat the symptoms
      of herpes simplex virus infection on the lips and around the mouth (cold sores).
      Although this medicine will not cure herpes simplex, it may help the sores to
      heal faster and relieve some of the pain and discomfort. Acyclovir is an antiviral
      agent (treats a virus) and hydrocortisone is a steroid (cortisone-like) medicine.
  - type: paragraph
    text: This medicine is available only with your doctor's prescription.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Cream
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies have not been performed on the relationship of age
        to the effects of acyclovir and hydrocortisone topical combination in children
        younger than 6 years of age. Safety and efficacy have not been established.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Although appropriate studies on the relationship of age to the effects
        of acyclovir and hydrocortisone topical combination have not been performed
        in the geriatric population, no geriatric-specific problems have been documented
        to date.
    subsections: []
  - heading: Breastfeeding
    level: 3
    content:
    - type: paragraph
      text: There are no adequate studies in women for determining infant risk when
        using this medication during breastfeeding. Weigh the potential benefits against
        the potential risks before taking this medication while breastfeeding.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. Tell your healthcare professional if you are
        taking any other prescription or nonprescription (over-the-counter [OTC])
        medicine.
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Weak immune system—This medicine may not work properly in patients with this
        condition.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: Use this medicine only as directed by your doctor to benefit your condition
      as much as possible. Do not use more of it, do not use it more often, and do
      not use it for a longer time than your doctor ordered.
  - type: paragraph
    text: This medicine comes with a patient information insert. Read and follow the
      instructions carefully. Ask your doctor if you have any questions.
  - type: paragraph
    text: This medicine is only for cold sores on the lips and around the mouth .
      Do not get it in your eyes, inside your mouth or nose, or on the genital area.
      If the cream does get on these areas, rinse it off with water right away.
  - type: paragraph
    text: To help clear up your herpes infection, keep using this medicine for the
      full time of treatment , even if your symptoms begin to clear up after a few
      days. Do not miss any doses.
  - type: paragraph
    text: 'To use:'
  - type: list
    ordered: false
    items:
    - Wash your hands with soap and water before and after using the cream.
    - Clean and dry the affected area before applying the cream.
    - Apply a thin layer to the affected area that covers the cold sore.
    - Do not rub the cream into the cold sore. Rubbing may spread the virus to other
      areas around your mouth or make your cold sore worse.
    - Do not cover the cold sore or the area around the cold sore with a bandage.
    - Do not bathe, shower, or swim until 30 minutes after applying the medicine.
  subsections:
  - heading: Dosing
    level: 3
    content:
    - type: paragraph
      text: The dose of this medicine will be different for different patients. Follow
        your doctor's orders or the directions on the label. The following information
        includes only the average doses of this medicine. If your dose is different,
        do not change it unless your doctor tells you to do so.
    - type: paragraph
      text: The amount of medicine that you take depends on the strength of the medicine.
        Also, the number of doses you take each day, the time allowed between doses,
        and the length of time you take the medicine depend on the medical problem
        for which you are using the medicine.
    - type: list
      ordered: false
      items:
      - 'For topical dosage form (cream): For cold sores: Adults and children 6 years
        of age and older—Apply to the affected area 5 times per day for 5 days. Children
        younger than 6 years of age—Use and dose must be determined by your doctor.'
    - type: list
      ordered: false
      items:
      - 'For cold sores: Adults and children 6 years of age and older—Apply to the
        affected area 5 times per day for 5 days. Children younger than 6 years of
        age—Use and dose must be determined by your doctor.'
    - type: list
      ordered: false
      items:
      - Adults and children 6 years of age and older—Apply to the affected area 5
        times per day for 5 days.
      - Children younger than 6 years of age—Use and dose must be determined by your
        doctor.
    subsections: []
  - heading: Missed Dose
    level: 3
    content:
    - type: paragraph
      text: If you miss a dose of this medicine, apply it as soon as possible. However,
        if it is almost time for your next dose, skip the missed dose and go back
        to your regular dosing schedule.
    subsections: []
  - heading: Storage
    level: 3
    content:
    - type: paragraph
      text: Store the medicine in a closed container at room temperature, away from
        heat, moisture, and direct light. Keep from freezing.
    - type: paragraph
      text: Keep out of the reach of children.
    - type: paragraph
      text: Do not keep outdated medicine or medicine no longer needed.
    - type: paragraph
      text: Ask your healthcare professional how you should dispose of any medicine
        you do not use.
    subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is very important that your doctor check your progress after you use
      this medicine to see if the medicine is working properly.
  - type: paragraph
    text: If your symptoms do not improve within 2 weeks, or if they become worse,
      check with your doctor.
  - type: paragraph
    text: Do not use cosmetics or other skin care products (eg, make-up, sun screen,
      lip balm) on the treated area.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor immediately if any of the following side effects
      occur:'
  subsections:
  - heading: Rare
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Burning, itching, redness, rash, swelling, soreness, or tingling at the application
        site
      - change in skin color at the application site
      - dryness or flaking of the skin
      - flushing or redness of the skin
      - unusually warm skin
    subsections: []
  - heading: Incidence not known
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Blistering, burning, or crusting of the skin
      - itching, scaling, severe redness, soreness, or swelling of the skin
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: February 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Acyclovir and hydrocortisone (topical application route) - Side effects & dosage
  - type: paragraph
    text: DRG-20074300
  subsections: []
