title: Fibrinogen and thrombin, human (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Evarrest
    - type: paragraph
      text: Raplixa
    - type: paragraph
      text: Tachosil
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Fibrinogen and thrombin human topical powder or patch is used to help control
      bleeding during surgery when other procedures to close a wound or incision,
      such as stitches, bands, and heat cannot be used. This medicine is a fibrin
      sealant.
  - type: paragraph
    text: This medicine contains man-made proteins (fibrinogen and thrombin) that
      are used to stop bleeding by helping the blood to clot.
  - type: paragraph
    text: This medicine is to be given only by or under the supervision of your doctor.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Sheet
    - Solution
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies have not been performed on the relationship of age
        to the effects of fibrinogen and thrombin human topical powder or patch in
        the pediatric population. Safety and efficacy have not been established.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated geriatric-specific
        problems that would limit the usefulness of fibrinogen and thrombin human
        topical powder or patch in the elderly.
    subsections: []
  - heading: Breastfeeding
    level: 3
    content:
    - type: paragraph
      text: There are no adequate studies in women for determining infant risk when
        using this medication during breastfeeding. Weigh the potential benefits against
        the potential risks before taking this medication while breastfeeding.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. Tell your healthcare professional if you are
        taking any other prescription or nonprescription (over-the-counter [OTC])
        medicine.
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Allergy to human blood products, history of or
      - Arterial bleeding, severe or brisk or
      - Infection on any part of the body or at the application site—Should not be
        used in patients with these conditions.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: A doctor or other trained health professional will give you this medicine.
      This medicine is applied only to your skin or incision during surgery.
  - type: paragraph
    text: This medicine may be used with a sponge or a spray applicator. It should
      not be given as an injection .
  subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is very important that your doctor check you closely while you are receiving
      this medicine to make sure it is working properly.
  - type: paragraph
    text: This medicine may increase your chance of having blood clotting problems.
      Tell your doctor right away if you have a sudden or severe headache, problems
      with vision or speech, chest pain, trouble breathing or swallowing, swelling
      or tenderness in your leg, or numbness or weakness while you are receiving this
      medicine.
  - type: paragraph
    text: This medicine may cause a serious type of allergic reaction, including anaphylaxis,
      which can be life-threatening and requires immediate medical attention. Tell
      your doctor right away if you have a rash, itching, hives, chest pain, dizziness
      or lightheadedness, trouble breathing, trouble swallowing, or any swelling of
      your hands, face, or mouth after receiving this medicine.
  - type: paragraph
    text: This medicine is made from donated human blood. Some human blood products
      have transmitted certain viruses to people who have received them, although
      the risk is low. Human donors and donated blood are both tested for viruses
      to keep the transmission risk low. Talk with your doctor about this risk if
      you are concerned.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor or nurse immediately if any of the following side
      effects occur:'
  subsections:
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Blurred vision
      - confusion
      - dizziness
      - dizziness, faintness, or lightheadedness when getting up suddenly from a lying
        or sitting position
      - headache
      - nervousness
      - pain at the application site
      - pale skin
      - pounding in the ears
      - slow or fast heartbeat
      - sweating
      - troubled breathing with exertion
      - unusual bleeding or bruising
      - unusual tiredness or weakness
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Bleeding
    - type: paragraph
      text: 'Some side effects may occur that usually do not need medical attention.
        These side effects may go away during treatment as your body adjusts to the
        medicine. Also, your health care professional may be able to tell you about
        ways to prevent or reduce some of these side effects. Check with your health
        care professional if any of the following side effects continue or are bothersome
        or if you have any questions about them:'
    subsections: []
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Constipation
      - fever
      - itching skin
      - nausea
      - vomiting
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: July 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Fibrinogen and thrombin, human (topical application route) - Side effects &
      uses
  - type: paragraph
    text: DRG-20146758
  subsections: []
