title: Halobetasol and tazarotene (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Duobrii
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Halobetasol and tazarotene combination topical is used to treat plaque psoriasis.
      Plaque psoriasis is a skin disease with red patches and white scales that do
      not go away.
  - type: paragraph
    text: Halobetasol is a corticosteroid that helps relieve redness, itching, swelling,
      or other discomfort caused by certain skin conditions. Tazarotene works by making
      the skin less red and reducing the number and size of lesions of the skin.
  - type: paragraph
    text: This medicine is available only with your doctor's prescription.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Lotion
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies have not been performed on the relationship of age
        to the effects of halobetasol and tazarotene combination topical in the pediatric
        population. Safety and efficacy have not been established.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated geriatric-specific
        problems that would limit the usefulness of halobetasol topical in the elderly.
    subsections: []
  - heading: Breastfeeding
    level: 3
    content:
    - type: paragraph
      text: There are no adequate studies in women for determining infant risk when
        using this medication during breastfeeding. Weigh the potential benefits against
        the potential risks before taking this medication while breastfeeding.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. Tell your healthcare professional if you are
        taking any other prescription or nonprescription (over-the-counter [OTC])
        medicine.
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Adrenal gland problem or
      - Diabetes or
      - Eye or vision problems (eg, cataracts, glaucoma)—Use with caution. May make
        these conditions worse.
    - type: list
      ordered: false
      items:
      - Broken skin at the application site or
      - Liver failure—Use with caution. The chance of side effects may be increased.
    - type: list
      ordered: false
      items:
      - Eczema (skin disorder) or
      - Sunburn—Should not be used in patients with these conditions. May increase
        risk of skin burning and irritation.
    - type: list
      ordered: false
      items:
      - Skin infection—Must be treated first before using this medicine.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: It is very important that you use this medicine only as directed by your
      doctor . Do not use more of it, do not use it more often, and do not use it
      for a longer time than your doctor ordered. To do so may cause unwanted side
      effects or skin irritation.
  - type: paragraph
    text: This medicine is for use only on the skin . Do not get it into your eyes,
      nose, mouth, groin, or vagina, or apply it on your face or under your arms.
      If it does get on these areas, rinse it off right away with water.
  - type: paragraph
    text: 'To use:'
  - type: list
    ordered: false
    items:
    - Wash your hands with soap and water before and after using this medicine.
    - Make sure your skin is dry before you use the medicine.
    - Apply a thin layer of this medicine to the affected area of the skin. Rub it
      in gently.
    - Do not bandage or otherwise wrap the skin being treated unless directed to do
      so by your doctor.
  - type: paragraph
    text: This medicine should only be used for skin conditions that your doctor is
      treating. Check with your doctor before using it for other conditions, especially
      if you think that a skin infection may be present . This medicine should not
      be used to treat certain kinds of skin infections or conditions, such as severe
      burns.
  subsections:
  - heading: Dosing
    level: 3
    content:
    - type: paragraph
      text: The dose of this medicine will be different for different patients. Follow
        your doctor's orders or the directions on the label. The following information
        includes only the average doses of this medicine. If your dose is different,
        do not change it unless your doctor tells you to do so.
    - type: paragraph
      text: The amount of medicine that you take depends on the strength of the medicine.
        Also, the number of doses you take each day, the time allowed between doses,
        and the length of time you take the medicine depend on the medical problem
        for which you are using the medicine.
    - type: list
      ordered: false
      items:
      - 'For topical dosage form (lotion): For plaque psoriasis: Adults—Apply to the
        affected area of the skin once a day. Children—Use and dose must be determined
        by the doctor.'
    - type: list
      ordered: false
      items:
      - 'For plaque psoriasis: Adults—Apply to the affected area of the skin once
        a day. Children—Use and dose must be determined by the doctor.'
    - type: list
      ordered: false
      items:
      - Adults—Apply to the affected area of the skin once a day.
      - Children—Use and dose must be determined by the doctor.
    subsections: []
  - heading: Missed Dose
    level: 3
    content:
    - type: paragraph
      text: If you miss a dose of this medicine, apply it as soon as possible. However,
        if it is almost time for your next dose, skip the missed dose and go back
        to your regular dosing schedule.
    subsections: []
  - heading: Storage
    level: 3
    content:
    - type: paragraph
      text: Keep out of the reach of children.
    - type: paragraph
      text: Do not keep outdated medicine or medicine no longer needed.
    - type: paragraph
      text: Ask your healthcare professional how you should dispose of any medicine
        you do not use.
    - type: paragraph
      text: Store the medicine in a closed container at room temperature, away from
        heat, moisture, and direct light. Keep from freezing.
    - type: paragraph
      text: Do not freeze.
    subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is important that your doctor check your progress at regular visits to
      make sure that this medicine is working properly and to check for unwanted effects.
  - type: paragraph
    text: If your symptoms do not improve within a few days or weeks, or if they become
      worse, check with your doctor.
  - type: paragraph
    text: Using this medicine while you are pregnant can harm your unborn baby. Use
      an effective form of birth control to keep from getting pregnant. If you think
      you have become pregnant while using this medicine, tell your doctor right away.
  - type: paragraph
    text: To make sure you are not pregnant when you start using this medicine, you
      may need to start using it during a normal menstrual period. Also, you must
      have a negative pregnancy test within 2 weeks before you start using this medicine.
  - type: paragraph
    text: 'Using too much of this medicine or using it for a long time may increase
      your risk of having adrenal gland problems. The risk is greater for children
      and patients who use large amounts for a long time. Talk to your doctor right
      away if you have more than one of these symptoms while you are using this medicine:
      blurred vision, dizziness or fainting, a fast, irregular, or pounding heartbeat,
      increased thirst or urination, irritability, or unusual tiredness or weakness.'
  - type: paragraph
    text: Avoid exposing your skin to wind, cold weather, and sunlight, even on cloudy
      days. Your skin will be more prone to sunburn, dryness, or irritation. Do not
      use a sunlamp or tanning bed. Use a sunscreen or sunblock lotion with a sun
      protection factor (SPF) of at least 15 on a regular basis. Wear protective clothing
      and hats and stay out of direct sunlight, especially between the hours of 10
      a.m. and 3 p.m.
  - type: paragraph
    text: It is likely that your skin may become irritated with normal use of this
      medicine. You should not stop using tazarotene unless your skin becomes too
      red, dry, puffy, or otherwise irritated. If severe irritation occurs, contact
      your doctor.
  - type: paragraph
    text: Check with your doctor right away if blurred vision, difficulty with reading,
      or any other change in vision occurs during or after treatment. Your doctor
      may want your eyes be checked by an ophthalmologist (eye doctor).
  - type: paragraph
    text: Do not take other medicines unless they have been discussed with your doctor.
      This includes prescription or nonprescription (over-the-counter [OTC]) medicines
      and herbal or vitamin supplements.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor immediately if any of the following side effects
      occur:'
  subsections:
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Blistering, burning, crusting, drying, or flaking of the skin
      - itching, scaling, severe redness, soreness, or swelling of the skin
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Breakdown, weakness, falling off, or wasting away of the skin
      - burning, itching, and pain in hairy areas, pus at the root of the hair
      - skin scrape or irritation
      - thinning of skin with easy bruising, especially when used on the face or areas
        where the skin may touch or rub together
    - type: paragraph
      text: 'Some side effects may occur that usually do not need medical attention.
        These side effects may go away during treatment as your body adjusts to the
        medicine. Also, your health care professional may be able to tell you about
        ways to prevent or reduce some of these side effects. Check with your health
        care professional if any of the following side effects continue or are bothersome
        or if you have any questions about them:'
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Pain at the application site
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: February 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Halobetasol and tazarotene (topical application route) - Side effects & dosage
  - type: paragraph
    text: DRG-20463373
  subsections: []
