title: Minocycline (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Amzeeq
    - type: paragraph
      text: Cleeravue-M
    - type: paragraph
      text: Zilxi
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Minocycline topical foam is used to treat moderate to severe acne vulgaris.
      This medicine also treats inflammatory lesions (pimples and red bumps) caused
      by rosacea.
  - type: paragraph
    text: Minocycline belongs to the class of medicines known as tetracycline antibiotics.
      However, this medicine is not used to prevent or treat infections.
  - type: paragraph
    text: This medicine is available only with your doctor's prescription.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Foam
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated pediatric-specific
        problems that would limit the usefulness of minocycline topical foam to treat
        acne vulgaris in children 9 years of age and older. However, safety and efficacy
        have not been established in children younger than 9 years of age to treat
        acne vulgaris , and have not been established in children to treat inflammatory
        lesions of rosacea .
    - type: paragraph
      text: Minocycline may cause permanent discoloration of the teeth and slow down
        bone growth. This medicine should not be given to children 8 years of age
        and younger, unless directed by the child's doctor.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated geriatric-specific
        problems that would limit the usefulness of minocycline topical foam in the
        elderly. However, elderly patients are more sensitive to the effects of this
        medicine than younger adults.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. Tell your healthcare professional if you are
        taking any other prescription or nonprescription (over-the-counter [OTC])
        medicine.
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Diarrhea or
      - Eye or vision problems—Use with caution. May make these conditions worse.
    - type: list
      ordered: false
      items:
      - Infection of the skin at or near the place of application or
      - Large sores, broken skin, or severe skin injury at the place of application—The
        chance of side effects may be increased.
    - type: list
      ordered: false
      items:
      - Kidney disease or
      - Liver disease—Use with caution. The effects may be increased because of slower
        removal of the medicine from the body.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: It is very important that you use this medicine only as directed by your
      doctor . Do not use more of it, do not use it more often, and do not use it
      for a longer time than your doctor ordered. To do so may cause unwanted side
      effects or skin irritation.
  - type: paragraph
    text: This medicine comes with a patient information leaflet. Read and follow
      the instructions carefully. Ask your doctor if you have any questions.
  - type: paragraph
    text: This medicine is for use on the skin only . Do not get it into your eyes,
      nose, mouth, or vagina. Do not use it on skin areas that have cuts, scrapes,
      or burns. If it does get on these areas, rinse it off right away with water.
  - type: paragraph
    text: To help clear up your skin condition completely, it is very important that
      you keep using this medicine for the full time of treatment . Do not miss any
      doses.
  - type: paragraph
    text: This medicine should only be used for skin conditions that your doctor is
      treating. Check with your doctor first before using it for other conditions,
      especially if you think that a skin infection may be present . This medicine
      should not be used to treat certain kinds of skin infections or conditions,
      such as severe burns.
  - type: paragraph
    text: 'To use the topical foam:'
  - type: list
    ordered: false
    items:
    - Wash your hands with soap and water before and after using this medicine.
    - Allow the foam can to warm to room temperature before using it for the first
      time. Shake it well.
    - 'Apply a thin layer of this medicine to the affected area of the skin. For acne:
      Rub Amzeeq™ foam gently into the acne-affected parts of the face and other parts
      of the body (eg, neck, shoulders, arms, back, chest). For rosacea: Gently rub
      Zilxi™ foam over all areas of the face. You may need to use additional foam
      to make sure the entire face is treated.'
    - Apply it at the same time each day at least 1 hour before bedtime.
    - Do not bathe, shower, or swim for at least 1 hour after application.
  - type: list
    ordered: false
    items:
    - 'For acne: Rub Amzeeq™ foam gently into the acne-affected parts of the face
      and other parts of the body (eg, neck, shoulders, arms, back, chest).'
    - 'For rosacea: Gently rub Zilxi™ foam over all areas of the face. You may need
      to use additional foam to make sure the entire face is treated.'
  subsections:
  - heading: Dosing
    level: 3
    content:
    - type: paragraph
      text: The dose of this medicine will be different for different patients. Follow
        your doctor's orders or the directions on the label. The following information
        includes only the average doses of this medicine. If your dose is different,
        do not change it unless your doctor tells you to do so.
    - type: paragraph
      text: The amount of medicine that you take depends on the strength of the medicine.
        Also, the number of doses you take each day, the time allowed between doses,
        and the length of time you take the medicine depend on the medical problem
        for which you are using the medicine.
    - type: list
      ordered: false
      items:
      - 'For topical dosage form (foam): For inflammatory lesions caused by rosacea:
        Adults—Apply to the affected area of the skin once a day, at least 1 hour
        before bedtime. Children—Use and dose must be determined by your doctor. For
        moderate to severe acne: Adults and children 9 years of age and older—Apply
        to the affected area of the skin once a day, at least 1 hour before bedtime.
        Children younger than 9 years of age—Use and dose must be determined by your
        doctor.'
    - type: list
      ordered: false
      items:
      - 'For inflammatory lesions caused by rosacea: Adults—Apply to the affected
        area of the skin once a day, at least 1 hour before bedtime. Children—Use
        and dose must be determined by your doctor.'
      - 'For moderate to severe acne: Adults and children 9 years of age and older—Apply
        to the affected area of the skin once a day, at least 1 hour before bedtime.
        Children younger than 9 years of age—Use and dose must be determined by your
        doctor.'
    - type: list
      ordered: false
      items:
      - Adults—Apply to the affected area of the skin once a day, at least 1 hour
        before bedtime.
      - Children—Use and dose must be determined by your doctor.
    - type: list
      ordered: false
      items:
      - Adults and children 9 years of age and older—Apply to the affected area of
        the skin once a day, at least 1 hour before bedtime.
      - Children younger than 9 years of age—Use and dose must be determined by your
        doctor.
    subsections: []
  - heading: Missed Dose
    level: 3
    content:
    - type: paragraph
      text: If you miss a dose of this medicine, apply it as soon as possible. However,
        if it is almost time for your next dose, skip the missed dose and go back
        to your regular dosing schedule.
    subsections: []
  - heading: Storage
    level: 3
    content:
    - type: paragraph
      text: Keep out of the reach of children.
    - type: paragraph
      text: Do not keep outdated medicine or medicine no longer needed.
    - type: paragraph
      text: Ask your healthcare professional how you should dispose of any medicine
        you do not use.
    - type: paragraph
      text: Store the medicine in a closed container at room temperature, away from
        heat, moisture, and direct light. Keep from freezing.
    - type: paragraph
      text: Store the foam can at room temperature for 90 days, away from heat, flames,
        smoke, and direct light. Do not store in the refrigerator.
    - type: paragraph
      text: The foam can is flammable. Do not keep this medicine inside a car where
        it could be exposed to extreme heat. Do not poke holes in the canister or
        throw it into a fire, even if the canister is empty.
    subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is very important that your doctor check your or your child's progress
      at regular visits to see if the medicine is working properly. Blood tests may
      be needed to check for unwanted effects.
  - type: paragraph
    text: If your or your child's symptoms do not improve within a few days, or if
      they become worse, check with your doctor.
  - type: paragraph
    text: Using this medicine while you are pregnant can harm your unborn baby. Use
      an effective form of birth control to keep from getting pregnant. If you think
      you have become pregnant while using this medicine, tell your doctor right away.
  - type: paragraph
    text: Minocycline may cause diarrhea, and in some cases it can be severe. It may
      occur 2 months or more after you stop taking this medicine. Do not take any
      medicine to treat diarrhea without first checking with your doctor. Diarrhea
      medicines may make the diarrhea worse or make it last longer. If you have any
      questions about this or if mild diarrhea continues or gets worse, check with
      your doctor.
  - type: paragraph
    text: Tell your doctor right away if you have confusion, diarrhea, loss of appetite,
      sleepiness, tiredness, unusual bleeding, or yellow eyes or skin. These could
      be symptoms of a serious liver problem.
  - type: paragraph
    text: This medicine may cause dizziness, lightheadedness, or spinning feeling.
      Do not drive or do anything else that could be dangerous until you know how
      this medicine affects you .
  - type: paragraph
    text: This medicine may cause intracranial hypertension (increased pressure in
      the head). This is more likely to occur in women of childbearing age who are
      overweight. Tell your doctor right away if you have a headache, blurred vision,
      or other change in vision.
  - type: paragraph
    text: Autoimmune syndromes (including drug-induced lupus-like syndrome, autoimmune
      hepatitis, vasculitis and serum sickness) may occur while using this medicine.
      Call your doctor right away if you or your child have a fever, rash, joint pain,
      or body weakness while using this medicine.
  - type: paragraph
    text: 'Minocycline may cause your skin to be more sensitive to sunlight than it
      is normally. Exposure to sunlight, even for short periods of time, may cause
      skin rash, itching, redness or other discoloration of the skin, or a severe
      sunburn. When you begin taking this medicine:'
  - type: list
    ordered: false
    items:
    - Stay out of direct sunlight, especially between the hours of 10:00 a.m. and
      3:00 p.m., if possible.
    - Wear protective clothing, including a hat. Also, wear sunglasses.
    - Apply a sunblock product that has a sun protection factor (SPF) number of at
      least 15. Some patients may require a product with a higher SPF number, especially
      if they have a fair complexion. If you have any questions about this, check
      with your doctor.
    - Do not use a sun lamp or tanning bed or booth.
    - If you have a severe reaction from the sun, check with your doctor right away.
  - type: paragraph
    text: Serious skin or allergic reactions, which can be life-threatening, may occur
      during treatment with this medicine. Call your doctor right away if you have
      blistering or peeling of the skin, chest pain, dark urine, fever, hives, irregular
      heartbeat, skin rash, sores in the mouth, stomach pain, swelling in the legs,
      ankles, or feet, swelling of the face, eyes, lips, tongue, or throat, trouble
      breathing or swallowing, or yellow eyes or skin.
  - type: paragraph
    text: Check with your doctor right away if you have darkening of the skin, scars,
      teeth, or gums.
  - type: paragraph
    text: Make sure any doctor or dentist who treats you knows that you are using
      this medicine. You may need to stop using this medicine several days before
      you have medical tests.
  - type: paragraph
    text: Do not use cosmetics or other skin care products on the treated areas.
  - type: paragraph
    text: Do not take other medicines unless they have been discussed with your doctor.
      This includes prescription or nonprescription (over-the-counter [OTC]) medicines
      and herbal or vitamin supplements.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor immediately if any of the following side effects
      occur:'
  subsections:
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Redness, dryness, itching, peeling, or discoloration of the treated skin
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Diarrhea
    subsections: []
  - heading: Incidence not known
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Blurred vision
      - change in ability to see colors, especially blue or yellow
      - fever
      - general feeling of discomfort or illness
      - headache
      - increased sensitivity of the skin to sunlight
      - itching or skin rash
      - joint or muscle pain
      - loss of appetite
      - redness or other discoloration of the skin
      - severe abdominal or stomach cramps and pain
      - severe sunburn
      - unusual tiredness or weakness
      - vomiting
      - watery and severe diarrhea, which may also be bloody
    - type: paragraph
      text: 'Some side effects may occur that usually do not need medical attention.
        These side effects may go away during treatment as your body adjusts to the
        medicine. Also, your health care professional may be able to tell you about
        ways to prevent or reduce some of these side effects. Check with your health
        care professional if any of the following side effects continue or are bothersome
        or if you have any questions about them:'
    subsections: []
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Burning, darkening, dryness, flushing, itching, peeling, redness, or stinging
        on the skin, especially when used on the face
      - raised, dark red, wart-like spots on the skin, especially when used on the
        face
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Headache
    subsections: []
  - heading: Incidence not known
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Darkening of the skin, teeth, or gums
      - dizziness or lightheadedness
      - feeling of constant movement of self or surroundings
      - sensation of spinning
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: February 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Minocycline (topical application route) - Side effects & dosage
  - type: paragraph
    text: DRG-20475090
  subsections: []
