title: Oxymetazoline (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Rhofade
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Oxymetazoline topical cream is used to treat facial redness caused by rosacea
      that does not go away (persistent) in adults.
  - type: paragraph
    text: This medicine is available only with your doctor's prescription.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Cream
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies have not been performed on the relationship of age
        to the effects of oxymetazoline topical cream in the pediatric population.
        Safety and efficacy have not been established.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated geriatric-specific
        problems that would limit the usefulness of oxymetazoline topical cream in
        the elderly.
    subsections: []
  - heading: Breastfeeding
    level: 3
    content:
    - type: paragraph
      text: There are no adequate studies in women for determining infant risk when
        using this medication during breastfeeding. Weigh the potential benefits against
        the potential risks before taking this medication while breastfeeding.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. When you are taking this medicine, it is especially
        important that your healthcare professional know if you are taking any of
        the medicines listed below. The following interactions have been selected
        on the basis of their potential significance and are not necessarily all-inclusive.
    - type: paragraph
      text: Using this medicine with any of the following medicines is not recommended.
        Your doctor may decide not to treat you with this medication or change some
        of the other medicines you take.
    - type: list
      ordered: false
      items:
      - Isocarboxazid
      - Phenelzine
    - type: paragraph
      text: Using this medicine with any of the following medicines is usually not
        recommended, but may be required in some cases. If both medicines are prescribed
        together, your doctor may change the dose or how often you use one or both
        of the medicines.
    - type: list
      ordered: false
      items:
      - Amineptine
      - Amitriptyline
      - Amitriptylinoxide
      - Amoxapine
      - Amphetamine
      - Carteolol
      - Carvedilol
      - Clomipramine
      - Desipramine
      - Dextroamphetamine
      - Dibenzepin
      - Doxepin
      - Furazolidone
      - Imipramine
      - Insulin Aspart, Recombinant
      - Iproniazid
      - Isocarboxazid
      - Labetalol
      - Landiolol
      - Levobunolol
      - Linezolid
      - Lisdexamfetamine
      - Lofepramine
      - Melitracen
      - Methylene Blue
      - Metipranolol
      - Moclobemide
      - Nadolol
      - Nialamide
      - Nortriptyline
      - Opipramol
      - Oxprenolol
      - Penbutolol
      - Pindolol
      - Practolol
      - Procarbazine
      - Propranolol
      - Protriptyline
      - Rasagiline
      - Safinamide
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Blood circulation problems or
      - Enlarged prostate or
      - Heart or blood vessel disease, severe or unstable or uncontrolled or
      - Hypertension (high blood pressure), uncontrolled or
      - Hypotension (low blood pressure), uncontrolled or
      - Irritated skin or open sores on the face or
      - Narrow-angle glaucoma or
      - Raynaud syndrome or
      - Sjören syndrome or
      - Scleroderma or
      - Stroke, history of or
      - Thromboangiitis obliterans—Use with caution. May make these conditions worse.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: Use this medicine exactly as directed by your doctor . Do not use more of
      it, do not use it more often, and do not use it for a longer time than your
      doctor ordered. To do so may increase the chance of side effects.
  - type: paragraph
    text: This medicine should come with a patient information leaflet. Read and follow
      these instructions carefully. Ask your doctor if you have any questions.
  - type: paragraph
    text: 'To use:'
  - type: list
    ordered: false
    items:
    - This medicine is for use only in your face. Do not get any of it in your eyes,
      mouth, or vagina. Rinse it off right away if it does get on these areas.
    - If you are using the pump for the first time, prime it by holding the pump upright
      and press down several times until the cream is dispensed onto a tissue. Pump
      three more times onto the tissue and throw away the tissue.
    - Press down on the pump one time to dispense a pea-sized amount of the cream
      to your fingertip.
    - Apply a thin layer of the cream to cover the entire face (forehead, nose, cheeks,
      chin). Do not apply the cream to irritated skin or open wounds.
    - Wash your hands after applying the medicine.
  subsections:
  - heading: Dosing
    level: 3
    content:
    - type: paragraph
      text: The dose of this medicine will be different for different patients. Follow
        your doctor's orders or the directions on the label. The following information
        includes only the average doses of this medicine. If your dose is different,
        do not change it unless your doctor tells you to do so.
    - type: paragraph
      text: The amount of medicine that you take depends on the strength of the medicine.
        Also, the number of doses you take each day, the time allowed between doses,
        and the length of time you take the medicine depend on the medical problem
        for which you are using the medicine.
    - type: list
      ordered: false
      items:
      - 'For oral dosage form (cream): For treatment of facial redness caused by rosacea:
        Adults—Apply a thin layer to the entire face once a day. Children—Use and
        dose must be determined by your doctor.'
    - type: list
      ordered: false
      items:
      - 'For treatment of facial redness caused by rosacea: Adults—Apply a thin layer
        to the entire face once a day. Children—Use and dose must be determined by
        your doctor.'
    - type: list
      ordered: false
      items:
      - Adults—Apply a thin layer to the entire face once a day.
      - Children—Use and dose must be determined by your doctor.
    subsections: []
  - heading: Missed Dose
    level: 3
    content:
    - type: paragraph
      text: If you miss a dose of this medicine, apply it as soon as possible. However,
        if it is almost time for your next dose, skip the missed dose and go back
        to your regular dosing schedule.
    subsections: []
  - heading: Storage
    level: 3
    content:
    - type: paragraph
      text: Store the medicine in a closed container at room temperature, away from
        heat, moisture, and direct light. Keep from freezing.
    - type: paragraph
      text: Keep out of the reach of children.
    - type: paragraph
      text: Do not keep outdated medicine or medicine no longer needed.
    - type: paragraph
      text: Ask your healthcare professional how you should dispose of any medicine
        you do not use.
    subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is very important that your doctor check your progress at regular visits
      . This will allow your doctor to see if the medicine is working properly and
      to decide if you should continue to use it.
  - type: paragraph
    text: If your condition does not improve within a few days, or if it becomes worse,
      check with your doctor.
  - type: paragraph
    text: You will also need to have your blood pressure measured before starting
      this medicine and while you are using it. If you notice any change to your recommended
      blood pressure, call your doctor right away. If you have questions about this,
      talk to your doctor.
  - type: paragraph
    text: Check with your doctor immediately if blurred vision, eye pain, or any other
      change in vision occurs during or after treatment. Your doctor may want you
      to have your eyes checked by an ophthalmologist (eye doctor).
  - type: paragraph
    text: Do not use this medicine for a skin problem that has not been checked by
      your doctor.
  - type: paragraph
    text: Do not use cosmetics or other skin care products on the treated skin areas.
  - type: paragraph
    text: Do not take other medicines unless they have been discussed with your doctor.
      This includes prescription or nonprescription (over-the-counter [OTC]) medicines
      and herbal or vitamin supplements.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor immediately if any of the following side effects
      occur:'
  subsections:
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Blistering, crusting, irritation, itching, or reddening of the skin
      - cracked, dry, scaly skin
      - swelling or pain at the application site
      - worsening of rosacea pimples
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: September 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Oxymetazoline (topical application route) - Side effects & dosage
  - type: paragraph
    text: DRG-20406026
  subsections: []
