title: Thrombin, bovine (topical application route)
sections:
- heading: Brand Name
  level: 2
  content: []
  subsections:
  - heading: US Brand Name
    level: 3
    content:
    - type: paragraph
      text: Thrombin-JMI
    subsections: []
  - heading: Canadian Brand Name
    level: 3
    content:
    - type: paragraph
      text: Thrombinar
    - type: paragraph
      text: Thrombostat
    subsections: []
- heading: Description
  level: 2
  content:
  - type: paragraph
    text: Thrombin, bovine topical solution is used to help control minor bleeding
      during surgery.
  - type: paragraph
    text: This medicine is to be given only by or under the direct supervision of
      your doctor.
  - type: paragraph
    text: 'This product is available in the following dosage forms:'
  - type: list
    ordered: false
    items:
    - Powder for Solution
  subsections: []
- heading: Before Using
  level: 2
  content:
  - type: paragraph
    text: 'In deciding to use a medicine, the risks of taking the medicine must be
      weighed against the good it will do. This is a decision you and your doctor
      will make. For this medicine, the following should be considered:'
  subsections:
  - heading: Allergies
    level: 3
    content:
    - type: paragraph
      text: Tell your doctor if you have ever had any unusual or allergic reaction
        to this medicine or any other medicines. Also tell your health care professional
        if you have any other types of allergies, such as to foods, dyes, preservatives,
        or animals. For non-prescription products, read the label or package ingredients
        carefully.
    subsections: []
  - heading: Pediatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies have not been performed on the relationship of age
        to the effects of thrombin, bovine topical solution in the pediatric population.
        Safety and efficacy have not been established.
    subsections: []
  - heading: Geriatric
    level: 3
    content:
    - type: paragraph
      text: Appropriate studies performed to date have not demonstrated geriatric-specific
        problems that would limit the usefulness of thrombin, bovine topical solution
        in the elderly. However, elderly patients are more likely to have age-related
        kidney, liver, or heart problems, which may require caution and an adjustment
        in the dose for patients receiving this medicine.
    subsections: []
  - heading: Breastfeeding
    level: 3
    content:
    - type: paragraph
      text: There are no adequate studies in women for determining infant risk when
        using this medication during breastfeeding. Weigh the potential benefits against
        the potential risks before taking this medication while breastfeeding.
    subsections: []
  - heading: Drug Interactions
    level: 3
    content:
    - type: paragraph
      text: Although certain medicines should not be used together at all, in other
        cases two different medicines may be used together even if an interaction
        might occur. In these cases, your doctor may want to change the dose, or other
        precautions may be necessary. Tell your healthcare professional if you are
        taking any other prescription or nonprescription (over-the-counter [OTC])
        medicine.
    subsections: []
  - heading: Other Interactions
    level: 3
    content:
    - type: paragraph
      text: Certain medicines should not be used at or around the time of eating food
        or eating certain types of food since interactions may occur.  Using alcohol
        or tobacco with certain medicines may also cause interactions to occur.  Discuss
        with your healthcare professional the use of your medicine with food, alcohol,
        or tobacco.
    subsections: []
  - heading: Other Medical Problems
    level: 3
    content:
    - type: paragraph
      text: 'The presence of other medical problems may affect the use of this medicine.
        Make sure you tell your doctor if you have any other medical problems, especially:'
    - type: list
      ordered: false
      items:
      - Active bleeding, severe or
      - Bovine thrombin or factor V antibodies, known or suspected—Should not be used
        in patients with these conditions.
    - type: list
      ordered: false
      items:
      - Bleeding problems or
      - Blood clotting problems—Use with caution. May make these conditions worse.
    subsections: []
- heading: Proper Use
  level: 2
  content:
  - type: paragraph
    text: A nurse or other trained health professional will give you this medicine
      in a medical facility. This medicine is applied only to your skin or incision
      during surgery. This medicine should not be given as an injection .
  subsections: []
- heading: Precautions
  level: 2
  content:
  - type: paragraph
    text: It is very important that your doctor check your progress closely to make
      sure that this medicine is working properly. Blood tests may be needed to check
      for unwanted effects.
  - type: paragraph
    text: This medicine may cause serious allergic reactions, including anaphylaxis,
      which can be life-threatening and require immediate medical attention. Check
      with your doctor right away if you have chest tightness, cough, difficulty swallowing,
      dizziness, fast heartbeat, hives, itching, skin rash, puffiness or swelling
      of the eyelids or around the eyes, face, lips, or tongue. or unusual tiredness
      or weakness.
  - type: paragraph
    text: Check with your doctor right away if you have tenderness, pain, swelling,
      warmth, skin discoloration, and prominent superficial veins over affected area.
      These may be symptoms of blood clotting problems.
  subsections: []
- heading: Side Effects
  level: 2
  content:
  - type: paragraph
    text: Along with its needed effects, a medicine may cause some unwanted effects.
      Although not all of these side effects may occur, if they do occur they may
      need medical attention.
  - type: paragraph
    text: 'Check with your doctor or nurse immediately if any of the following side
      effects occur:'
  subsections:
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Cough or hoarseness
      - difficulty breathing
      - fast heartbeat
      - fever or chills
      - hives, itching, skin rash
      - irritation
      - joint pain, stiffness, or swelling
      - lower back or side pain
      - pain in the chest, groin, or legs, especially the calves
      - painful or difficult urination
      - redness of the skin
      - severe, sudden headache
      - slurred speech
      - sudden loss of coordination
      - sudden, severe weakness or numbness in arm or leg
      - swelling of the eyelids, face, lips, hands, or feet
      - vision changes
    subsections: []
  - heading: Less common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Black, tarry stools
      - bleeding gums
      - blood in the urine or stools
      - blurred vision
      - confusion
      - dizziness, faintness, or lightheadedness when getting up suddenly from a lying
        or sitting position
      - fast, pounding, or irregular heartbeat or pulse
      - pale skin
      - pinpoint red spots on the skin
      - red, tender, or oozing skin at the incision
      - sweating
      - unusual bleeding or bruising
      - unusual tiredness or weakness
    subsections: []
  - heading: Incidence not known
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Bruising
      - collection of blood under the skin
      - coughing or vomiting blood
      - chest tightness
      - deep, dark purple bruise
      - difficulty swallowing
      - itching, pain, redness, or swelling
      - persistent bleeding or oozing from puncture sites, mouth, or nose
      - puffiness or swelling of the eyelids or around the eyes, face, lips, or tongue
    - type: paragraph
      text: 'Some side effects may occur that usually do not need medical attention.
        These side effects may go away during treatment as your body adjusts to the
        medicine. Also, your health care professional may be able to tell you about
        ways to prevent or reduce some of these side effects. Check with your health
        care professional if any of the following side effects continue or are bothersome
        or if you have any questions about them:'
    subsections: []
  - heading: More common
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Constipation
      - muscle spasms
      - nausea
      - trouble sleeping
      - vomiting
    subsections: []
  - heading: Incidence not known
    level: 3
    content:
    - type: list
      ordered: false
      items:
      - Swelling
    - type: paragraph
      text: Other side effects not listed may also occur in some patients. If you
        notice any other effects, check with your healthcare professional.
    - type: paragraph
      text: Call your doctor for medical advice about side effects. You may report
        side effects to the FDA at 1-800-FDA-1088.
    - type: paragraph
      text: 'Drug information provided by: Merative, Micromedex®'
    - type: paragraph
      text: 'Portions of this document last updated: February 01, 2025'
    - type: paragraph
      text: 'Copyright: © Merative US L.P. 1973, 2025. All rights reserved. Information
        is for End User''s use only and may not be sold, redistributed or otherwise
        used for commercial purposes.'
    subsections: []
- heading: Products & Services
  level: 2
  content:
  - type: list
    ordered: false
    items:
    - The Mayo Clinic Diet
  - type: list
    ordered: true
    items:
    - Drugs & Supplements
    - Thrombin, bovine (topical application route) - Side effects & uses
  - type: paragraph
    text: DRG-20558085
  subsections: []
